Add meeting minutes for 16 October 2020
AY2021S1-CS2103T-W16-3/tp pull request #118
Opened 2020-10-16 13:46 UTC by siddarth2824

Added meeting minutes for 16 October.

2020-10-16 15:26 UTC, wltan commented on docs/minutes/20201016.md
> +adjustments to make the process more convenient.
I think we should try to avoid newlines mid-sentence?

2020-10-16 15:26 UTC, wltan commented on docs/minutes/20201016.md
> +Fine$$e is coming into shape - Ian Yong, 2020
Would look better italicized IMO

2020-10-16 15:26 UTC, wltan commented on docs/minutes/20201016.md
> +Workflow changes:
Perhaps this could be a subheading instead?

2020-10-16 15:26 UTC, wltan commented on docs/minutes/20201016.md
> +    100% - prevent regression in test coverage
Same as above, combine with the previous line

2020-10-17 03:00 UTC, zhaojj2209 approved these changes
LGTM!

2020-10-17 05:01 UTC, wltan requested changes

2020-10-17 05:01 UTC, wltan commented on docs/minutes/20201016.md
> +Fine$$e is coming into shape - Ian Yong, 2020
My previous comment https://github.com/AY2021S1-CS2103T-W16-3/tp/pull/118#discussion_r506540945 was referring to Line 7, not Line 6

2020-10-17 05:09 UTC, ianyong requested changes

2020-10-17 05:09 UTC, ianyong commented on docs/minutes/20201016.md
> +    - Edit find commands to be similar to edit commands e.g find INDEX KEYWORD
```suggestion
    - Edit find commands to be similar to edit commands e.g `find INDEX KEYWORD`
```

2020-10-17 06:39 UTC, yongping827 requested changes

2020-10-17 06:39 UTC, yongping827 commented on docs/minutes/20201016.md
> +    - Add a class to store frequent expenses/incomes (such frequent expenses/incomes will be in a seperate list)
```suggestion
    - Add a class to store frequent expenses/incomes (such frequent expenses/incomes will be in a separate list)
```

2020-10-17 06:39 UTC, yongping827 commented on docs/minutes/20201016.md
> +    - In Analytics make use of `YearMonth` instead of `LocalDate`
```suggestion
    - In Analytics, make use of `YearMonth` instead of `LocalDate`
```

2020-10-17 06:39 UTC, yongping827 commented on docs/minutes/20201016.md
> + - Investigate feasibility of UI testing. If not viable, then remove it from the testing suit.
```suggestion
 - Investigate feasibility of UI testing. If not viable, then remove it from the testing suite.
```

2020-10-17 06:54 UTC, wltan approved these changes
LGTM

2020-10-17 06:59 UTC, yongping827 approved these changes
LGTM

2020-10-17 07:13 UTC, ianyong approved these changes
LGTM!

2020-10-17 07:15 UTC, merged