Add tests to increase code coverage for 'logic' components
AY2021S1-CS2103T-W16-3/tp pull request #119
Opened 2020-10-16 15:39 UTC by ianyong

Related to #115.

2020-10-16 18:10 UTC, yongping827 requested changes

2020-10-16 18:10 UTC, yongping827 commented on src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteExpenseCommandTest.java
> +        // ensures that outOfBoundIndex is still in bounds of finance tracker list
```suggestion
        // ensures that outOfBoundIndex is still within bounds of finance tracker list of expenses
```

2020-10-16 18:10 UTC, yongping827 commented on src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteIncomeCommandTest.java
> +        // ensures that outOfBoundIndex is still in bounds of finance tracker list
```suggestion
        // ensures that outOfBoundIndex is still within bounds of finance tracker list of incomes
```

2020-10-16 18:10 UTC, yongping827 commented on src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteCommandTest.java
Line 73
```
// ensures that outOfBoundIndex is still within bounds of finance tracker list of transactions
```

2020-10-17 06:31 UTC, yongping827 approved these changes
LGTM

2020-10-17 08:22 UTC, zhaojj2209 approved these changes
LGTM!

2020-10-17 08:23 UTC, merged