Update inforamtion for Siddarth
AY2021S1-CS2103T-W16-3/tp pull request #12
Opened 2020-09-21 14:06 UTC by siddarth2824

2020-09-21 14:14 UTC, ianyong commented on src/main/main.iml
> +</module>
Don't commit `.iml` files.

2020-09-21 14:14 UTC, ianyong commented on docs/team/siddarth2824.md
> +* **Tools**:
```suggestion
* **Tools**:

```

Newline at EOF.

2020-09-22 04:30 UTC, ianyong submitted a review, later dismissed
LGTM!

2020-09-22 04:53 UTC, yongping827 requested changes

2020-09-22 04:53 UTC, yongping827 commented on docs/AboutUs.md
> +* Responsibilities: Scheduling and Tracking, User Interface-In-Charge
```suggestion
* Responsibilities: Scheduling and Tracking, User Interface
```

2020-09-22 05:09 UTC, yongping827 approved these changes
LGTM

2020-09-22 05:11 UTC, ianyong approved these changes
LGTM!

2020-09-22 05:11 UTC, merged