Update layout of user guide
AY2021S1-CS2103T-W16-3/tp pull request #169
Opened 2020-10-24 10:28 UTC by siddarth2824

Refactored the layout of the user guide.

Changes:
- Added number to each section and subsection
- Added a glossary section

2020-10-24 12:19 UTC, ianyong requested changes
Other than that, looks good!

2020-10-24 12:19 UTC, ianyong commented on docs/UserGuide.md
> +Fine$$e is an integrated platform fully customized for tertiary and university students with the aim of helping you track your finances effectively. Fine$$e allows you to keep track of your incomes,
Add line breaks after every full stop. This will help us version control the document better. Same for the rest of the document.

2020-10-24 14:17 UTC, ianyong approved these changes
LGTM!

2020-10-24 14:24 UTC, yongping827 approved these changes
LGTM

2020-10-24 14:25 UTC, merged

2020-10-25 17:32 UTC, ianyong commented
Related to #131.