Add content to Analytics tab
AY2021S1-CS2103T-W16-3/tp pull request #177
Opened 2020-10-24 20:36 UTC by yongping827

Resolves #154.

Added bar charts showing the past total monthly expenses, incomes and savings.

2020-10-24 21:02 UTC, ianyong requested changes

2020-10-24 21:02 UTC, ianyong commented on src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/AnalyticsTabPane.java
> +    private BarChart<String, Number> savingsAnalyticsBarChart;
Don't leave gaps in between for consistency with the other classes.

2020-10-24 21:02 UTC, ianyong commented on src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/AnalyticsTabPane.java
> +        savingsAnalyticsLabel.setText("SAVINGS");
Since these are mostly the same, can they be generalised into a method? Or will these diverse significantly in the future?

2020-10-24 21:02 UTC, ianyong commented on src/main/resources/view/AnalyticsTabPane.fxml
> +<?import javafx.geometry.Insets?>
Reorder the imports to be alphabetical.

2020-10-24 22:02 UTC, zhaojj2209 approved these changes
LGTM!

2020-10-25 11:14 UTC, ianyong approved these changes
LGTM!

2020-10-25 11:15 UTC, merged