Add screenshots for bookmark commands
AY2021S1-CS2103T-W16-3/tp pull request #252
Opened 2020-10-30 18:04 UTC by siddarth2824

Added screenshots with annotations for the following section and commands:
* Bookmark Expense section preface
* Bookmark Income section preface
* `AddBookmarkExpenseCommand`
* `AddBookmarkIncomeCommand`
* `EditBookmarkExpenseCommand`
* `EditBookmarkIncomeCommand`
* `ConvertBookmarkExpenseCommand`
* `ConvertBookmarkIncomeCommand`

2020-10-30 19:10 UTC, ianyong requested changes

2020-10-30 19:10 UTC, ianyong commented on docs/UserGuide.md
> +Bookmark Expenses List Panel in the Expenses Tab
This line isn't very clear as to what it's for. :/

![image](https://user-images.githubusercontent.com/5585517/97747033-44afa100-1b26-11eb-8922-677e59839d75.png)

If it is meant to be captions to the image, perhaps we could work out some styling to use that makes its purpose more obvious?

Same for the other captions.

2020-10-31 06:21 UTC, ianyong commented on docs/UserGuide.md
> +Bookmark Expenses List Panel in the Expenses Tab
To be resolved in a separate PR. Issue #256 opened.

2020-10-31 06:21 UTC, ianyong approved these changes
LGTM!

2020-10-31 06:48 UTC, yongping827 approved these changes
LGTM

2020-10-31 06:48 UTC, merged