Modify base commands to throw error on execute
AY2021S1-CS2103T-W16-3/tp pull request #269
Opened 2020-11-02 17:53 UTC by yongping827

Resolves #125.

2020-11-03 12:04 UTC, ianyong requested changes
In each of the base commands, there are now unused strings. Possible to delete those?

2020-11-03 13:13 UTC, ianyong submitted a review, later dismissed
LGTM!

2020-11-03 13:50 UTC, ianyong approved these changes
LGTM!

2020-11-04 13:47 UTC, wltan approved these changes
LGTM!

2020-11-04 13:48 UTC, merged