Adds switching of tabs when executing add commands
AY2021S1-CS2103T-W16-3/tp pull request #288
Opened 2020-11-06 09:26 UTC by zhaojj2209

Resolves #270.

Executing `add-expense` or `add-income` commands now switches the UI to the Expenses and Incomes tab respectively.

This behaviour is now also documented in the user guide.

2020-11-06 10:25 UTC, siddarth2824 requested changes
There is inconsistent switching behaviour for the `set-expense-limit` and `set-savings-goal` command. These commands should ideally switch the tabs, to maintain consistency for tabs switching, to the `Overview` tab as the `Overview` tab consists information related to expense limit and savings goal.

2020-11-06 19:05 UTC, yongping827 requested changes
The removal of `assertCommandSuccess` from `SetExpenseLimitCommandTest` and `SetSavingsGoalCommandTest` seems unnecessary.

Consider implementing another overloaded `assertCommandSuccess` that has a parameter `Tab`. This way the `Tab` can be compared by `CommandResult::equals` rather than an additional `assertEquals`.

2020-11-07 15:10 UTC, yongping827 requested changes

2020-11-07 15:10 UTC, yongping827 commented on src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
> +                                            Model expectedModel) {
```suggestion
            Model expectedModel) {
```
This should be the more appropriate indentation level, according to the standard. Ignore the indentation IntelliJ gives you.

2020-11-07 15:10 UTC, yongping827 commented on src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
>                                              Model expectedModel, boolean isCalculateBudgetInfo) {
```suggestion
            Model expectedModel, boolean isCalculateBudgetInfo) {
```

2020-11-07 15:10 UTC, yongping827 commented on src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
> +                                            Model expectedModel, boolean isCalculateBudgetInfo, Tab tabToSwitchTo) {
```suggestion
            Model expectedModel, boolean isCalculateBudgetInfo, Tab tabToSwitchTo) {
```

2020-11-07 16:17 UTC, ianyong approved these changes
LGTM!

2020-11-07 17:19 UTC, yongping827 approved these changes
LGTM

2020-11-07 17:26 UTC, siddarth2824 approved these changes
LGTM!

2020-11-07 17:27 UTC, merged