Rename seedu.address.model classes
AY2021S1-CS2103T-W16-3/tp pull request #39
Opened 2020-09-27 15:30 UTC by yongping827

Partially address #38. 

The following classes, including all related fields and methods, are renamed as:
- Person → Transaction
- Name → Name
- Phone → Amount
- Tags → Category
- Email → Date

2020-09-27 15:34 UTC, ianyong requested changes
Update the package names too to `ay2021s1-cs2103-w16-3.finesse` as discussed.

Edit: My bad, hyphens are illegal characters. How about `ay2021s1_cs2103_w16_3.finesse` as recommended [here](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)?

2020-09-27 15:47 UTC, wltan requested changes

2020-09-27 15:47 UTC, wltan commented on LICENSE
> -copies of the Software, and to permit persons to whom the Software is
These don't look like intentional changes :/

2020-09-27 15:47 UTC, wltan commented on docs/AboutUs.md
> +You can reach us at the date <ay2021s1-cs2103t-w16-3@googlegroups.com>
Should also revert this change as well

2020-09-27 15:55 UTC, ianyong requested changes

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +    public static Date parseEmail(String email) throws ParseException {
`parseEmail` should be renamed to `parseDate` with the corresponding parameter renamed. Same for all other instances.

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +    public static Category parseTag(String tag) throws ParseException {
`parseTag` should be renamed to `parseCategory` with the corresponding parameter renamed. Same for all other instances.

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +    public static Amount parsePhone(String phone) throws ParseException {
`parsePhone` should be renamed to `parseAmount` with the corresponding parameter renamed. Same for all other instances.

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +     * Parses a {@code String phone} into a {@code Amount}.
```suggestion
     * Parses an {@code String amount} into a {@code Amount}.
```

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
>       * @throws ParseException if the given {@code phone} is invalid.
```suggestion
     * @throws ParseException if the given {@code amount} is invalid.
```

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
>       * @throws ParseException if the given {@code email} is invalid.
```suggestion
     * @throws ParseException if the given {@code date} is invalid.
```

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +     * Parses a {@code String tag} into a {@code Category}.
```suggestion
     * Parses a {@code String category} into a {@code Category}.
```

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
>       * @throws ParseException if the given {@code tag} is invalid.
```suggestion
     * @throws ParseException if the given {@code category} is invalid.
```

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +     * Parses {@code Collection<String> tags} into a {@code Set<Category>}.
```suggestion
     * Parses {@code Collection<String> categories} into a {@code Set<Category>}.
```

2020-09-27 15:55 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +    public static Set<Category> parseTags(Collection<String> tags) throws ParseException {
`parseTags` should be renamed to `parseCategories` with the corresponding parameter renamed. Same for all other instances.

2020-09-27 16:08 UTC, wltan commented
> Update the package names too to `ay2021s1-cs2103-w16-3.finesse` as discussed.
> 
> Edit: My bad, hyphens are illegal characters. How about `ay2021s1_cs2103_w16_3.finesse` as recommended [here](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)?

Recommend doing this in a separate PR. Refactoring the package would generate a large diff and make it difficult to review the model renaming.

2020-09-30 16:17 UTC, zhaojj2209 commented on src/main/java/seedu/address/model/person/Date.java
> + * Represents a Transaction's email in the address book.
```suggestion
 * Represents a Transaction's date in the address book.
```

2020-09-30 16:17 UTC, zhaojj2209 commented on src/main/java/seedu/address/model/person/Date.java
> +    public Date(String email) {
The argument name here should probably be changed from `email` to `date`. The JavaDoc should also be changed accordingly.

2020-09-30 16:17 UTC, zhaojj2209 commented on src/main/java/seedu/address/model/person/Date.java
>       * Returns if a given string is a valid email.
```suggestion
     * Returns if a given string is a valid date.
```

2020-09-30 16:43 UTC, zhaojj2209 requested changes
The UI currently encounters NullPointerExceptions when the application starts up; to resolve, the following files need to be refactored.

PersonListCard.fxml: Rename to TransactionListCard.fxml
PersonListPanel.fxml: Rename to TransactionListPanel.fxml, with a change in line 7
MainWindow.fxml: Change in line 53

2020-09-30 16:43 UTC, zhaojj2209 commented on src/main/resources/view/MainWindow.fxml
>            </padding>
In line 53, `"personListPanelPlaceholder"` should be changed to `"transactionListPanelPlaceholder"`.

2020-10-01 06:04 UTC, zhaojj2209 approved these changes
LGTM!

2020-10-01 12:39 UTC, wltan requested changes

2020-10-01 12:39 UTC, wltan commented on docs/DeveloperGuide.md
> +The UI consists of a `MainWindow` that is made up of parts e.g.`CommandBox`, `ResultDisplay`, `TransacionListPanel`, `StatusBarFooter` etc. All these, including the `MainWindow`, inherit from the abs
Minor typo:
```suggestion
The UI consists of a `MainWindow` that is made up of parts e.g.`CommandBox`, `ResultDisplay`, `TransactionListPanel`, `StatusBarFooter` etc. All these, including the `MainWindow`, inherit from the abstract `UiPart` class.
```

2020-10-01 13:16 UTC, ianyong requested changes

2020-10-01 13:16 UTC, ianyong commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> +        EditCommand.EditTransactionDescriptor editTransactionDescriptor = new EditCommand.EditTransactionDescriptor();
Could you import `EditCommand.EditTransactionDescriptor` instead?

2020-10-01 13:48 UTC, ianyong approved these changes
LGTM!

2020-10-01 14:01 UTC, wltan approved these changes
LGTM!

Pitest report: https://ay2021s1-cs2103t-w16-3.github.io/reports/pitest/202010012150/

2020-10-01 14:04 UTC, merged