Refactor logic to allow for UI-dependent behaviour
AY2021S1-CS2103T-W16-3/tp pull request #83
Opened 2020-10-10 17:45 UTC by ianyong

Resolves #81.

2020-10-10 18:31 UTC, zhaojj2209 requested changes
Just some changes to capitalisation for consistency.

2020-10-10 18:31 UTC, zhaojj2209 commented on src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/Logic.java
>       * @return the result of the command execution.
```suggestion
     * @return The result of the command execution.
```

2020-10-10 18:31 UTC, zhaojj2209 commented on src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
> +     * @return the currently selected tab.
```suggestion
     * @return The currently selected tab.
```

2020-10-10 18:31 UTC, zhaojj2209 commented on src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
> +     * @param currentTab the currently selected tab.
```suggestion
     * @param currentTab The currently selected tab.
```

2020-10-11 07:28 UTC, zhaojj2209 approved these changes
LGTM!

2020-10-11 09:17 UTC, yongping827 requested changes

2020-10-11 09:17 UTC, yongping827 commented on src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
> +     * @throws ParseException If the user input does not conform the expected format.
```suggestion
     * @throws ParseException If the user input does not conform to the expected format.
```

2020-10-11 09:17 UTC, yongping827 commented on src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
> +        EXPENSES,
Either
```suggestion
        INCOMES,
        EXPENSES,
```
or
```suggestion
        INCOME,
        EXPENSE,
```

2020-10-11 09:17 UTC, yongping827 commented on src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
> +    public void parseCommand_unrecognisedInputWhenOverviewTab_throwsParseException() {
```suggestion
    public void parseCommand_unrecognizedInputWhenOverviewTab_throwsParseException() {
```
Also in other similar places.

2020-10-11 09:22 UTC, yongping827 approved these changes
LGTM

2020-10-11 09:22 UTC, merged